# Generated by Django 5.0.7 on 2025-10-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Mężczyzna'), ('female', 'Kobieta'), ('other', 'Inna/nie podano')], default='', max_length=10),
        ),
    ]
